import type * as IconsNamespace from '../icons/all-icons';

type IconName = keyof typeof IconsNamespace;

interface IconMetadata {
    tags: string[];
}

export const iconMetadata: {
    readonly [key in IconName]: IconMetadata | undefined;
} = {
    /* eslint-disable @typescript-eslint/naming-convention */
    AddIcon: undefined,
    ArrowDownRightAndArrowUpLeftIcon: undefined,
    ArrowExpanderDownIcon: undefined,
    ArrowExpanderLeftIcon: undefined,
    ArrowExpanderRightIcon: undefined,
    ArrowExpanderUpIcon: undefined,
    ArrowLeftFromLineIcon: undefined,
    ArrowPartialRotateLeftIcon: undefined,
    ArrowRightToLineIcon: undefined,
    ArrowRotateRightIcon: undefined,
    ArrowURotateLeftIcon: undefined,
    ArrowUpLeftAndArrowDownRightIcon: undefined,
    ArrowsMaximizeIcon: undefined,
    ArrowsRepeatIcon: undefined,
    BarsIcon: undefined,
    BellIcon: undefined,
    BellAndCommentIcon: undefined,
    BellCircleIcon: undefined,
    BellSolidCircleIcon: undefined,
    BlockWithRibbonIcon: undefined,
    CalendarIcon: undefined,
    ChartDiagramIcon: undefined,
    ChartDiagramChildFocusIcon: undefined,
    ChartDiagramParentFocusIcon: undefined,
    ChartDiagramParentFocusTwoChildIcon: undefined,
    CheckIcon: undefined,
    CheckDotIcon: undefined,
    CircleIcon: undefined,
    CircleBrokenIcon: undefined,
    CircleCheckIcon: undefined,
    CirclePartialBrokenIcon: undefined,
    CircleSlashIcon: undefined,
    CircleXIcon: undefined,
    ClipboardIcon: undefined,
    ClockIcon: undefined,
    ClockCogIcon: undefined,
    ClockTriangleIcon: undefined,
    CloneIcon: undefined,
    CloudUploadIcon: undefined,
    CloudWithArrowIcon: undefined,
    CogIcon: undefined,
    CogDatabaseIcon: undefined,
    CogDatabaseInsetIcon: undefined,
    CogSmallCogIcon: undefined,
    CogZoomedIcon: undefined,
    CommentIcon: undefined,
    ComputerAndMonitorIcon: undefined,
    CopyIcon: undefined,
    CopyTextIcon: undefined,
    DashboardBuilderIcon: undefined,
    DashboardBuilderLegendIcon: undefined,
    DashboardBuilderTemplatesIcon: undefined,
    DashboardBuilderTileIcon: undefined,
    DatabaseIcon: undefined,
    DatabaseCheckIcon: undefined,
    DesktopIcon: undefined,
    DonutChartIcon: undefined,
    DotSolidDotStrokeIcon: undefined,
    DownloadIcon: undefined,
    ElectronicChipZoomedIcon: undefined,
    ExclamationMarkIcon: undefined,
    EyeIcon: undefined,
    FancyAIcon: undefined,
    FileIcon: undefined,
    FileDrawerIcon: undefined,
    FileSearchIcon: undefined,
    FilterIcon: undefined,
    FloppyDiskCheckmarkIcon: undefined,
    FloppyDiskStarArrowRightIcon: undefined,
    FloppyDiskThreeDotsIcon: undefined,
    FolderIcon: undefined,
    FolderOpenIcon: undefined,
    ForwardSlashIcon: undefined,
    FourDotsSquareIcon: undefined,
    FunctionIcon: undefined,
    GaugeSimpleIcon: undefined,
    GridThreeByThreeIcon: undefined,
    GridTwoByTwoIcon: undefined,
    HammerIcon: undefined,
    HashtagIcon: undefined,
    HomeIcon: undefined,
    HourglassIcon: undefined,
    IndeterminantCheckboxIcon: undefined,
    InfoIcon: undefined,
    InfoCircleIcon: undefined,
    KeyIcon: {
        tags: ['access-control', 'active-directory']
    },
    LaptopIcon: undefined,
    LayerGroupIcon: undefined,
    LightningBoltIcon: undefined,
    LinkIcon: undefined,
    LinkCancelIcon: undefined,
    ListIcon: undefined,
    ListTreeIcon: undefined,
    ListTreeDatabaseIcon: undefined,
    LockIcon: undefined,
    MagnifyingGlassIcon: undefined,
    MarkdownIcon: undefined,
    MinusIcon: undefined,
    MinusWideIcon: undefined,
    MobileIcon: undefined,
    NotebookIcon: undefined,
    PasteIcon: undefined,
    PencilIcon: undefined,
    PotWithLidIcon: undefined,
    QuestionIcon: undefined,
    RunningArrowIcon: undefined,
    ServerIcon: undefined,
    ShareSquareIcon: undefined,
    ShieldCheckIcon: undefined,
    ShieldXmarkIcon: undefined,
    SignalBarsIcon: undefined,
    SineGraphIcon: undefined,
    SkipArrowIcon: undefined,
    SpinnerIcon: undefined,
    SquareCheckIcon: undefined,
    SquareTIcon: undefined,
    TIcon: undefined,
    TabletIcon: undefined,
    TagIcon: undefined,
    TagsIcon: undefined,
    TargetCrosshairsIcon: undefined,
    TargetCrosshairsProgressIcon: undefined,
    ThreeDotsLineIcon: undefined,
    ThumbtackIcon: undefined,
    TileSizeIcon: undefined,
    TimesIcon: undefined,
    TrashIcon: undefined,
    TriangleIcon: undefined,
    TrueFalseRectangleIcon: undefined,
    UnlinkIcon: undefined,
    UnlockIcon: undefined,
    UploadIcon: undefined,
    UserIcon: undefined,
    WatchIcon: undefined,
    WaveformIcon: undefined,
    WebviCustomIcon: undefined,
    WebviHostIcon: undefined,
    WindowCodeIcon: undefined,
    WindowTextIcon: undefined,
    WrenchHammerIcon: undefined,
    XmarkIcon: undefined,
    XmarkCheckIcon: undefined
    /* eslint-enable @typescript-eslint/naming-convention */
};
