import type * as TokenNamesNamespace from './design-token-names';

type TokenNames = typeof TokenNamesNamespace;
type TokenNameKeys = keyof TokenNames;

export const comments: { [key in TokenNameKeys]: string | undefined } = {
    actionColorRgbPartial: undefined,
    applicationBackgroundColor: 'Background color for the application.',
    fillColorSelected: undefined,
    fillColorSelectedRgbPartial: undefined,
    fillColorSelectedHover: undefined,
    fillColorHover: undefined,
    borderColor: undefined,
    borderColorRgbPartial: undefined,
    failColor: undefined,
    warningColor: undefined,
    passColor: undefined,
    borderColorHover: undefined,
    iconColor: undefined,
    popupBoxShadowColor: undefined,
    popupBorderColor: undefined,
    controlHeight: undefined,
    standardPadding: undefined,
    labelHeight: undefined,
    borderWidth: undefined,
    iconSize: undefined,
    drawerWidth: undefined,
    fontFamily: undefined,
    labelFontFamily: undefined,
    groupLabelFontFamily: undefined,
    drawerHeaderFontFamily: undefined,
    labelFontSize: undefined,
    contentFontSize: undefined,
    groupLabelFontSize: undefined,
    drawerHeaderFontSize: undefined,
    groupLabelFontWeight: undefined,
    labelFontWeight: undefined,
    labelFontColor: undefined,
    groupLabelFontColor: undefined,
    contentFontColor: undefined,
    buttonContentFontColor: undefined,
    labelFontColorDisabled: undefined,
    labelTextTransform: undefined,
    groupLabelTextTransform: undefined,
    contentFontColorDisabled: undefined,
    smallDelay: undefined,
    mediumDelay: undefined,
    drawerAnimationDurationMs: undefined,
    passwordRevealFilter: undefined,
    direction: undefined
};
