// Note: This icon file is manually created, not generated by the icon build script.
// For instructions on creating multi-color icons, see CONTRIBUTING.md
import { circlePartialBroken16X16 } from '@ni/nimble-tokens/dist/icons/js/multicolor';
import { css } from '@ni/fast-element';
import {
    MultiColorIcon,
    registerMultiColorIcon
} from '../icon-base/multi-color';
import {
    bodyDisabledFontColor,
    warningColor
} from '../theme-provider/design-tokens';

declare global {
    interface HTMLElementTagNameMap {
        'nimble-icon-circle-partial-broken': IconCirclePartialBroken;
    }
}

/**
 * A multi-color icon component for the 'circlePartialBroken' icon.
 * This icon uses two theme colors:
 * - cls-1: bodyDisabledFontColor (circle outline)
 * - cls-2: warningColor (broken segment)
 */
export class IconCirclePartialBroken extends MultiColorIcon {
    public constructor() {
        super(circlePartialBroken16X16 as any);
    }
}

/**
 * Static styles for the circle-partial-broken multi-color icon.
 * Each layer color is set as a CSS custom property on the :host element.
 */
export const circlePartialBrokenStyles = css`
    :host {
        --ni-nimble-icon-layer-1-color: ${bodyDisabledFontColor};
        --ni-nimble-icon-layer-2-color: ${warningColor};
    }
`;

registerMultiColorIcon(
    'icon-circle-partial-broken',
    IconCirclePartialBroken,
    circlePartialBrokenStyles
);
export const iconCirclePartialBrokenTag = 'nimble-icon-circle-partial-broken';
