// Note: This icon file is manually created, not generated by the icon build script.
// For instructions on creating multi-color icons, see CONTRIBUTING.md
import { circlePartialBroken16X16 } from '@ni/nimble-tokens/dist/icons/js';
import { registerIcon } from '../icon-base';
import { MultiColorIcon } from '../icon-base/multi-color';
import { multiColorTemplate } from '../icon-base/multi-color-template';
import {
    graphGridlineColor,
    warningColor
} from '../theme-provider/design-tokens';

declare global {
    interface HTMLElementTagNameMap {
        'nimble-icon-circle-partial-broken': IconCirclePartialBroken;
    }
}

/**
 * A multi-color icon component for the 'circlePartialBroken' icon.
 * This icon uses two theme colors:
 * - cls-1: graphGridlineColor (circle outline)
 * - cls-2: warningColor (broken segment)
 */
export class IconCirclePartialBroken extends MultiColorIcon {
    protected layerColors = [graphGridlineColor, warningColor];

    public constructor() {
        super(circlePartialBroken16X16);
    }
}

registerIcon(
    'icon-circle-partial-broken',
    IconCirclePartialBroken,
    multiColorTemplate
);
export const iconCirclePartialBrokenTag = 'nimble-icon-circle-partial-broken';
