on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - '@ni/nimble-tokens_v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install --global npm@7

    # Build
    - name: build tokens nuget
      run: npm run build:nuget -w @ni/nimble-tokens
    - uses: actions/upload-artifact@v2
      with:
        name: nuget package
        path: packages/**/*.nupkg
        if-no-files-found: error

    # Publish
    - if: startsWith(github.ref, 'refs/tags/@ni/nimble-tokens_v')
      name: nuget publish
      run: |
        nuget push *.nupkg -ApiKey ${{secrets.NUGET_TOKEN}} -Source "https://api.nuget.org/v3/index.json"