on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci

    # Build
    - name: calculate release version
      run: |
        export NIMBLE_VERSION=$(node -p "require('./packages/nimble-tokens/package.json').version")
        export NIMBLE_NUGET_PATH=$(pwd)"/packages/nimble-tokens/source/NimbleXamlTokens/bin/Release/NimbleXamlTokens."$NIMBLE_VERSION".nupkg"
        echo "NIMBLE_VERSION=$NIMBLE_VERSION" >> $GITHUB_ENV
        echo "NIMBLE_NUGET_PATH=$NIMBLE_NUGET_PATH" >> $GITHUB_ENV
    - name: build project and nuget
      run: dotnet pack ./packages/nimble-tokens/source/NimbleXamlTokens --configuration Release -p:PackageVersion=$NIMBLE_VERSION
    - uses: actions/upload-artifact@v2
      with:
        name: nuget package
        path: ${{env.NIMBLE_NUGET_PATH}}
        if-no-files-found: error

    # Publish
    - if: startsWith(github.ref, 'refs/tags/@ni/nimble-tokens_v')
      name: nuget publish
      run: |
        nuget push $NIMBLE_NUGET_PATH -ApiKey ${{secrets.NUGET_TOKEN}} -Source "https://api.nuget.org/v3/index.json"