# Defines steps which run _only_ on PRs into main. main.yml defines steps that run both on PR and on push

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            # Install dependencies.
            - uses: actions/setup-node@v1
              with:
                node-version: '12'
                registry-url: 'https://registry.npmjs.org'
            - run: npm install --global npm@7
            - run: npm ci

            # Check for beachball change file inside ./change
            - run: npm run check